environment:
  global:
    RANDOM_SEED: 0
    PYTHONUTF8: 1
    VIRTUALENV_PYTHONUTF8: 1
  matrix:
    - PYTHON_MAJOR: 3
      PYTHON_MINOR: 6
    - PYTHON_MAJOR: 3
      PYTHON_MINOR: 7
    - PYTHON_MAJOR: 3
      PYTHON_MINOR: 8

cache:
  - .venv -> poetry.lock

install:
  # Add Make and Python to the PATH
  - copy C:\MinGW\bin\mingw32-make.exe C:\MinGW\bin\make.exe
  - set PATH=%PATH%;C:\MinGW\bin
  - set PATH=C:\Python%PYTHON_MAJOR%%PYTHON_MINOR%;%PATH%
  - set PATH=C:\Python%PYTHON_MAJOR%%PYTHON_MINOR%\Scripts;%PATH%
  # Install system dependencies
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - set PATH=%USERPROFILE%\.poetry\bin;%PATH%
  - echo "Python UTF8 = %PYTHONUTF8%"
  - make doctor
  # Install project dependencies
  - make install

build: off

test_script:
  - make check
  - make test
  - make demo
