name: Windows

on:
  push:
  pull_request:
    branches: [ develop ]

jobs:
  Test:
    uses: ./.github/workflows/_common.yml
    with:
      basepath: 'D:\'
      os: "windows-latest"
      workpath: 'C:\a\doorstop\doorstop'
    secrets:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
